export const API_URL = "http://192.168.31.21:3000"
// export const API_URL = "http://localhost:3000"
export const WEB_URL = "http://localhost:5174"
//export const API_URL = "https://api.xavilaura.cat"
// export const WEB_URL = "https://enscasem.xavilaura.cat"